# configs/optuna_config.yaml
# =========================
# Hyperparameter search spaces for ML models

wandb:
  project: driver-monitoring-system
  entity: omarhariri-syrian-private-university

rf:
  n_trials: 30
  params:
    n_estimators: [100, 500]
    max_depth: [10, 40]
    min_samples_split: [2, 10]
    min_samples_leaf: [1, 5]

xgb:
  n_trials: 50
  params:
    n_estimators: [100, 1000]
    max_depth: [3, 12]
    learning_rate: [0.01, 0.2]
    subsample: [0.6, 1.0]
    colsample_bytree: [0.6, 1.0]
    min_child_weight: [1, 7]
